version: '3'
services:


  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:80'
    logging:
      driver: none
  api:
    build:
      dockerfile: Dockerfile
      context: ./creditBack
    volumes:
      - /app/node_modules
      - ./creditBack:/app
  front:
    build:
      dockerfile: Dockerfile
      context: ./creditFront
    volumes:
      - /app/node_modules
      - ./creditFront:/app
  
